name: Update RSS

on:
  schedule:
    - cron: "0 8 * * *"   # cada día a las 08:00 UTC
  workflow_dispatch:      # permite ejecutarlo a mano

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run script
        run: python generate_feed.py
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/feed.xml
          git commit -m "Update RSS feed" || echo "No changes"
          git push
