name: Update RSS

on:
  schedule:
    - cron: "0 8 * * *"   # cada día a las 08:00 UTC
  workflow_dispatch:      # botón "Run workflow" manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests beautifulsoup4
      - name: Build feed
        run: python generate_feed.py
      - name: Commit feed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/feed.xml
          git commit -m "Update RSS feed" || echo "No changes"
          git push
