name: Update RSS Feed

on:
  schedule:
    - cron: "0 */12 * * *"   # cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run RSS-Bridge
        run: |
          mkdir -p docs
          php rss-bridge/index.php \
            --action=display \
            --bridge=GoogleSearchBridge \
            --format=Atom \
            --q="site:20minutos.es/autor/li-borja-teran/" \
            > docs/feed.xml

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/feed.xml
          git commit -m "update feed" || echo "No changes"
          git push
